Controllers/FitnessPlusController.cs
using GymApplication.Data;
using GymApplication.Interface;
using GymApplication.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Globalization;
using static GymApplication.Models.BodyTypeViewModel;

namespace GymApplication.Controllers
{
    public class FitnessPlusController : Controller
    {
        private readonly IFitnessPlus main;

        public FitnessPlusController(IFitnessPlus mainProvider)
        {
            main = mainProvider;
        }

        #region AgeGroup
        public async Task<IActionResult> AgeGroups()
        {
            return View(await main.GetAllAgeGroups());
        }

        public async Task<IActionResult> CreateAgeGroup(int id)
        {
            return View(await main.GetAgeGroupById(id));
        }

        [HttpPost]
        public async Task<IActionResult> CreateAgeGroup([FromForm] AgeGroupViewModel model)
        {
            if (ModelState.IsValid)
            {
                if (await main.CreateOrUpdateAgeGroup(model))
                {
                    return RedirectToAction("AgeGroups");
                }
            }
            return View(model);
        }

        public async Task<IActionResult> AgeGroupDetails(int id)
        {
            return View(await main.GetAgeGroupById(id));
        }
        #endregion
        #region BodyType
        public async Task<IActionResult> BodyTypes()
        {
            return View(await main.GetAllBodyTypes());
        }

        public async Task<IActionResult> CreateBodyType(int id)
        {
            return View(await main.GetBodyTypeById(id));
        }

        [HttpPost]
        public async Task<IActionResult> CreateBodyType([FromForm] BodyTypeViewModel model)
        {
            if (ModelState.IsValid)
            {
                if (await main.CreateOrUpdateBodyType(model))
                {
                    return RedirectToAction("BodyTypes");
                }
            }
            return View(model);
        }

        public async Task<IActionResult> BodyTypeDetails(int id)
        {
            return View(await main.GetBodyTypeById(id));
        }
        #endregion
        #region BodyGoal
        public async Task<IActionResult> BodyGoals()
        {
            return View(await main.GetAllBodyGoals());
        }

        public async Task<IActionResult> CreateBodyGoal(int id)
        {
            return View(await main.GetBodyGoalById(id));
        }

        [HttpPost]
        public async Task<IActionResult> CreateBodyGoal([FromForm] BodyGoalViewModel model)
        {
            if (ModelState.IsValid)
            {
                if (await main.CreateOrUpdateBodyGoal(model))
                {
                    return RedirectToAction("BodyGoals");
                }
            }
            return View(model);
        }

        public async Task<IActionResult> BodyGoalDetails(int id)
        {
            return View(await main.GetBodyGoalById(id));
        }
        #endregion
        #region TargetBody
        public async Task<IActionResult> TargetBodies()
        {
            return View(await main.GetAllTargetBodies());
        }

        public async Task<IActionResult> CreateTargetBody(int id)
        {
            return View(await main.GetTargetBodyById(id));
        }

        [HttpPost]
        public async Task<IActionResult> CreateTargetBody([FromForm] TargetBodyViewModel model)
        {
            if (ModelState.IsValid)
            {
                if (await main.CreateOrUpdateTargetBody(model))
                {
                    return RedirectToAction("TargetBodies");
                }
            }
            return View(model);
        }

        public async Task<IActionResult> TargetBodyDetails(int id)
        {
            return View(await main.GetTargetBodyById(id));
        }
        #endregion
        #region ProblemArea
        public async Task<IActionResult> ProblemAreas()
        {
            return View(await main.GetAllProblemAreas());
        }

        public async Task<IActionResult> CreateProblemArea(int id)
        {
            return View(await main.GetProblemAreaById(id));
        }

        [HttpPost]
        public async Task<IActionResult> CreateProblemArea([FromForm] ProblemAreaViewModel model)
        {
            if (ModelState.IsValid)
            {
                if (await main.CreateOrUpdateProblemArea(model))
                {
                    return RedirectToAction("ProblemAreas");
                }
            }
            return View(model);
        }

        public async Task<IActionResult> ProblemAreaDetails(int id)
        {
            return View(await main.GetProblemAreaById(id));
        }
        #endregion
        #region StepDiet
        public async Task<IActionResult> StepDiets()
        {
            return View(await main.GetAllStepDiets());
        }

        public async Task<IActionResult> CreateStepDiet(int id)
        {
            return View(await main.GetStepDietById(id));
        }

        [HttpPost]
        public async Task<IActionResult> CreateStepDiet([FromForm] StepDietViewModel model)
        {
            if (ModelState.IsValid)
            {
                if (await main.CreateOrUpdateStepDiet(model))
                {
                    return RedirectToAction("StepDiets");
                }
            }
            return View(model);
        }

        public async Task<IActionResult> StepDietDetails(int id)
        {
            return View(await main.GetStepDietById(id));
        }
        #endregion
        #region StepWater
        public async Task<IActionResult> StepWaters()
        {
            return View(await main.GetAllStepWaters());
        }

        public async Task<IActionResult> CreateStepWater(int id)
        {
            return View(await main.GetStepWaterById(id));
        }

        [HttpPost]
        public async Task<IActionResult> CreateStepWater([FromForm] StepWaterViewModel model)
        {
            if (ModelState.IsValid)
            {
                if (await main.CreateOrUpdateStepWater(model))
                {
                    return RedirectToAction("StepWaters");
                }
            }
            return View(model);
        }

        public async Task<IActionResult> StepWaterDetails(int id)
        {
            return View(await main.GetStepWaterById(id));
        }
        #endregion
        #region StepWorkout
        public async Task<IActionResult> StepWorkouts()
        {
            return View(await main.GetAllStepWorkouts());
        }

        public async Task<IActionResult> CreateStepWorkout(int id)
        {
            return View(await main.GetStepWorkoutById(id));
        }

        [HttpPost]
        public async Task<IActionResult> CreateStepWorkout([FromForm] StepWorkoutViewModel model)
        {
            if (ModelState.IsValid)
            {
                if (await main.CreateOrUpdateStepWorkout(model))
                {
                    return RedirectToAction("StepWorkouts");
                }
            }
            return View(model);
        }

        public async Task<IActionResult> StepWorkoutDetails(int id)
        {
            return View(await main.GetStepWorkoutById(id));
        }
        #endregion
        #region StepWorkoutFrequency
        public async Task<IActionResult> StepWorkoutsFrequency()
        {
            return View(await main.GetAllWorkoutFrequencies());
        }

        public async Task<IActionResult> CreateStepWorkoutsFrequency(int id)
        {
            return View(await main.GetWorkoutFrequencyById(id));
        }

        [HttpPost]
        public async Task<IActionResult> CreateStepWorkoutsFrequency([FromForm] WorkoutFrequencyViewModel model)
        {
            if (ModelState.IsValid)
            {
                if (await main.CreateOrUpdateWorkoutFrequency(model))
                {
                    return RedirectToAction("StepWorkoutsFrequency");
                }
            }
            return View(model);
        }

        #endregion
        #region AdditionalGoal
        public async Task<IActionResult> AdditionalGoals()
        {
            return View(await main.GetAllAdditionalGoals());
        }

        public async Task<IActionResult> CreateAdditionalGoal(int id)
        {
            return View(await main.GetAdditionalGoalById(id));
        }

        [HttpPost]
        public async Task<IActionResult> CreateAdditionalGoal([FromForm] AdditionalGoalViewModel model)
        {
            if (ModelState.IsValid)
            {
                if (await main.CreateOrUpdateAdditionalGoal(model))
                {
                    return RedirectToAction("AdditionalGoals");
                }
            }
            return View(model);
        }

        public async Task<IActionResult> AdditionalGoalDetails(int id)
        {
            return View(await main.GetAdditionalGoalById(id));
        }
        #endregion
        #region PersonalInformation


        public async Task<IActionResult> PersonalInformationList()
        {
            var data = await main.GetAllPersonalInformationRecords();
            return View(data);
        }

        [AllowAnonymous]
        public async Task<IActionResult> PersonalInformationDetails(int pid)
        {
            return View(await main.GetDietPlanById(pid));

        }
        public async Task<IActionResult> PersonAllDetails(int id)
        {
            return View(await main.GetPersonalInformationById(id));

        }
        public async Task<IActionResult> PersonInfo(int id)
        {
            return View(await main.GetPersonalInformationById(id));

        }

        [AllowAnonymous]
        public async Task<IActionResult> PersonalInformation(int id)
        {
            var data = await main.GetPersonalInformationById(id);
            return View(data);
        }

        [AllowAnonymous]

Views/Shared/_AccountLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    @* <link rel="stylesheet" href="~/css/account.css" asp-append-version="true" /> *@
    @* <link href="~/css/Loginstyle.css" rel="stylesheet" /> *@

</head>
<body>

    <div>
        @RenderBody()
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html class="no-js" lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title> Fitness Tracking System  </title>

    <!-- ================= Favicon ================== -->
    <!-- Standard -->
    <link rel="shortcut icon" href="http://placehold.it/64.png/000/fff">
    <!-- Retina iPad Touch Icon-->
    <link rel="apple-touch-icon" sizes="144x144" href="http://placehold.it/144.png/000/fff">
    <!-- Retina iPhone Touch Icon-->
    <link rel="apple-touch-icon" sizes="114x114" href="http://placehold.it/114.png/000/fff">
    <!-- Standard iPad Touch Icon-->
    <link rel="apple-touch-icon" sizes="72x72" href="http://placehold.it/72.png/000/fff">
    <!-- Standard iPhone Touch Icon-->
    <link rel="apple-touch-icon" sizes="57x57" href="http://placehold.it/57.png/000/fff">

    <!-- Styles -->
    <link href="~/theme/assets/css/lib/select2/select2.min.css" rel="stylesheet" />
    <link href="~/theme/assets/css/lib/font-awesome.min.css" rel="stylesheet">
    <link href="~/theme/assets/css/lib/themify-icons.css" rel="stylesheet">
    <link href="~/theme/assets/css/lib/menubar/sidebar.css" rel="stylesheet">
    <link href="~/theme/assets/css/lib/bootstrap.min.css" rel="stylesheet">
    <link href="~/theme/assets/css/lib/helper.css" rel="stylesheet">
    <link href="~/theme/assets/css/style.css" rel="stylesheet">
    <link rel="icon" type="image/png" sizes="16x16" href="./images/favicon.png">
    <link href="~/theme/vendor/owl-carousel/css/owl.carousel.min.css" rel="stylesheet" />
    <link href="~/theme/vendor/owl-carousel/css/owl.theme.default.min.css" rel="stylesheet" />   
    <link href="~/theme/vendor/jqvmap/css/jqvmap.min.css" rel="stylesheet">
    <link href="~/theme/css/style.css" rel="stylesheet">
<link href="~/theme/assets/css/style.css" rel="stylesheet" /> 
    <link href="~/theme/vendor/datatables/css/jquery.datatables.min.css" rel="stylesheet" />
    <link href="~/theme/assets/css/lib/fontawesome-free-6.7.2-web/css/all.css" rel="stylesheet" />
    <link href="~/theme/assets/css/lib/fontawesome-free-6.7.2-web/css/all.min.css" rel="stylesheet" />

</head>
<body>
    <div class="sidebar sidebar-hide-to-small sidebar-shrink sidebar-gestures">
        <partial name="_SideMenuBar" />
    </div>
    @* <div class="header">
        <div class="container-fluid">
            <partial name="_Header" />
        </div>
    </div> *@
    <div class="content-wrap">
        <div class="main">
            <div class="container-fluid">
                @RenderBody()
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            <div class="footer">
                <p>
                Designed And Developed By  © Brindan Joshi & Shrijan ManSingh 
                </p>
            </div>
        </div>
    </div>
    <!-- JS
    ============================================ -->
    <!-- Vendors JS -->
    <!-- jquery vendor -->
   
    <script src="~/theme/assets/js/lib/jquery.min.js"></script>
    <script src="~/theme/assets/js/lib/jquery.nanoscroller.min.js"></script>
    <!-- nano scroller -->
    <script src="~/theme/assets/js/lib/menubar/sidebar.js"></script>
    <script src="~/theme/assets/js/lib/preloader/pace.min.js"></script>
    <!-- sidebar -->
    <!-- bootstrap -->
    <script src="~/theme/vendor/datatables/js/jquery.dataTables.min.js"></script>
    <script src="~/theme/js/plugins-init/datatables.init.js"></script>

    <script src="~/theme/assets/js/scripts.js"></script><script src="~/theme/assets/js/lib/select2/select2.full.min.js"></script>
    <!-- scripit init-->
    @RenderSection("Scripts", required: false)
</body>

</html>

Views/Shared/_SideMenuBar.cshtml
<div class="nano">
    <div class="nano-content">
        <!-- Logo -->
        <div class="logo" style="padding: 20px; text-align: center;">
            <a asp-controller="Home" asp-action="Index" style="font-size: 1.2rem; font-weight: bold; color: #fff;">
                <span>Fitness Tracking System</span>
            </a>
        </div>

        <!-- Sidebar Menu -->
        <ul class="sidebar-nav" style="list-style: none; padding-left: 0; font-size: 15px;">

            <!-- Main Label -->
            <li class="label" style="padding: 10px 20px; font-weight: 600; color: #aaa;">Main</li>

            <!-- Dashboard -->
            <li class="active">
                <a asp-controller="Home" asp-action="Index" style="display: flex; align-items: center; padding: 10px 20px; color: #fff;">
                    <i class="ti-home" style="margin-right: 10px;"></i> Dashboard
                </a>
            </li>

            <!-- Apps Section -->
            <li class="label" style="padding: 10px 20px; font-weight: 600; color: #aaa;">Apps</li>

            @if (User.IsInRole("Admin"))
            {
                <!-- Setup Section -->
                <li>
                    <a class="sidebar-sub-toggle" style="display: flex; align-items: center; padding: 10px 20px; color: #fff;">
                        <i class="ti-settings" style="margin-right: 10px;"></i> Setup
                        <span class="sidebar-collapse-icon ti-angle-down" style="margin-left: auto;"></span>
                    </a>
                    <ul style="padding-left: 20px;">
                        <li><a asp-controller="FitnessPlus" asp-action="AgeGroups"><i class="fa fa-child"></i> Age-Group</a></li>
                        <li><a asp-controller="FitnessPlus" asp-action="BodyTypes"><i class="fa fa-user"></i> Body Types</a></li>
                        <li><a asp-controller="FitnessPlus" asp-action="BodyGoals"><i class="fa fa-bullseye"></i> Body Goals</a></li>
                        <li><a asp-controller="FitnessPlus" asp-action="TargetBodies"><i class="fa fa-crosshairs"></i> Target Bodies</a></li>
                        <li><a asp-controller="FitnessPlus" asp-action="ProblemAreas"><i class="fa fa-exclamation-triangle"></i> Problem Areas</a></li>
                        <li><a asp-controller="FitnessPlus" asp-action="StepDiets"><i class="fa fa-utensils"></i> Step Diets</a></li>
                        <li><a asp-controller="FitnessPlus" asp-action="StepWaters"><i class="fa fa-tint"></i> Step Waters</a></li>
                        <li><a asp-controller="FitnessPlus" asp-action="StepWorkouts"><i class="fa fa-running"></i> Step Workouts</a></li>
                        <li><a asp-controller="FitnessPlus" asp-action="AdditionalGoals"><i class="fa fa-plus-circle"></i> Additional Goals</a></li>
                        <li><a asp-controller="FitnessPlus" asp-action="StepWorkoutsFrequency"><i class="fa fa-calendar-alt"></i> Step Workouts Frequency</a></li>
                    </ul>
                </li>

                <!-- Admin-Only Pages -->
                <li><a asp-controller="FitnessPlus" asp-action="PersonalInformationList"><i class="fa fa-users"></i> Registered Accounts</a></li>
                <li><a asp-controller="FitnessPlus" asp-action="RecommendedPlanList"><i class="fa fa-list"></i> Recommend Diet & Exercise</a></li>
            }
            else
            {
                <!-- User Pages -->
                <li><a asp-controller="FitnessPlus" asp-action="PersonalInformationList">👨‍🏫 My Profile</a></li>
                <li><a asp-controller="FitnessPlus" asp-action="RecommendedPlanList">🍽️ Diet Plan</a></li>
                <li><a asp-controller="FitnessPlus" asp-action="FitnessLog">🏋️ Fitness Plan</a></li>
                <li><a asp-controller="FitnessPlus" asp-action="ViewStatistics">❤️ Statistics</a></li>
            }

            <!-- Logout -->
            <li style="padding: 10px 20px;">
                <form asp-action="Logout" asp-controller="Account" asp-area="Identity" style="display: inline;">
                    @Html.AntiForgeryToken()
                    <button type="submit" style="background: none; border: none; padding: 0; cursor: pointer; color: inherit; font: inherit; display: flex; align-items: center;">
                        <i class="fa fa-sign-out-alt" style="margin-right: 8px;"></i> Logout
                    </button>
                </form>

            </li>

        </ul>
    </div>
</div>